import Head from 'next/head';
import Image from 'next/image';
import styled, {ThemeProvider} from 'styled-components';
import BoardView from '../components/BoardView';
import Header from '../components/Header';
import Sidebar from '../components/Sidebar';
import styles from '../styles/Home.module.css';
import {lightTheme} from '../themes';

const Container = styled.div`
  display: flex;
  width: 100wv;
  height: 100vh;
`;

const Main = styled.div`
  flex-grow: 1;
  height: 100%;
  display: flex;
  flex-direction: column;
`

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={lightTheme}>
        <Container>
          <Sidebar/>
          <Main>
            <Header/>
            <BoardView/>
          </Main>
        </Container>
      </ThemeProvider>
    </div>
  )
}
